//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class OrderProduct
    {
        public System.Guid Id { get; set; }
        public string ProductCode { get; set; }
        public string Title { get; set; }
        public string AdditionalTitle { get; set; }
        public string Unit { get; set; }
        public decimal PriceWithoutTax { get; set; }
        public System.Guid SubCategoryId { get; set; }
        public decimal Amount { get; set; }
        public System.Guid OrderId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
