//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public Package()
        {
            this.Products = new HashSet<Product>();
        }
    
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> PriceWithoutVAT { get; set; }
        public Nullable<decimal> Capacity { get; set; }
        public Nullable<int> AmountAvailable { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
